//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class p000053
    {
        public int kod { get; set; }
        public int kod_p000052 { get; set; }
        public Nullable<int> kod_p000051 { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual p000051 p000051 { get; set; }
        public virtual p000052 p000052 { get; set; }
    }
}
