//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class p000047
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p000047()
        {
            this.p000054 = new HashSet<p000054>();
        }
    
        public int kod { get; set; }
        public int kod_p000044 { get; set; }
        public int kod_p000045 { get; set; }
        public string number { get; set; }
    
        public virtual p000044 p000044 { get; set; }
        public virtual p000045 p000045 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p000054> p000054 { get; set; }
    }
}
