//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class p000046
    {
        public int kod { get; set; }
        public int kod_p000047 { get; set; }
        public System.DateTime date { get; set; }
        public bool status { get; set; }
    
        public virtual p000047 p000047 { get; set; }
    }
}
